"""Build taxonomy and comparison tables from structured paper cards.

This stage reads ``data/paper_cards.jsonl``, asks an LLM to synthesize a
taxonomy from the categories and key ideas, then generates a comparison table
for each paper and saves the cleaned output to ``data/comparison_table.csv``.
"""

from __future__ import annotations

import argparse
import os
import json
import logging
import sys
from collections import Counter, defaultdict
from datetime import datetime
import re
from dataclasses import dataclass
from pathlib import Path
from time import perf_counter, sleep

import pandas as pd
from dotenv import load_dotenv
# Load .env early so OpenAI client can read credentials at import time
load_dotenv()
from openai import OpenAI
from pydantic import BaseModel, ConfigDict, Field
from tenacity import Retrying, retry_if_exception_type, stop_after_attempt, wait_exponential


PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = PROJECT_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

LOGGER = logging.getLogger(__name__)
DEFAULT_CARDS_PATH = PROJECT_ROOT / "data" / "paper_cards.jsonl"
DEFAULT_TAXONOMY_PATH = PROJECT_ROOT / "data" / "taxonomy.md"
DEFAULT_COMPARISON_PATH = PROJECT_ROOT / "data" / "comparison_table.csv"
DEFAULT_DEBUG_DIR = PROJECT_ROOT / "data" / "debug"
DEFAULT_MODEL = "deepseek-v4-pro"
DEFAULT_SLEEP_SECONDS = 1.5
DEFAULT_BATCH_SIZE = 10


TAXONOMY_SYSTEM_PROMPT = """你是一位学术综述编辑与知识体系设计专家。

你的任务是：基于用户提供的论文技术标签与核心思想，构建一个层级清晰、术语统一、可用于文献综述写作的分类树（taxonomy）。

硬性要求：
1. 只能使用输入里的 best_fit_category、key_idea、title 信息进行归纳，不要引入外部知识。
2. 分类树必须结构清晰，尽量采用 2-4 层层级。
3. 类别命名要稳定、专业、可复用，避免过于口语化或重复。
4. 必须指出每个一级/二级类下面的代表性论文或典型技术特征。
5. 输出必须是可直接写入 Markdown 文件的正文，不要输出额外解释。
"""


COMPARISON_SYSTEM_PROMPT = """你是一位严格的学术综述助手，负责把论文卡片整理成方法对比表。

硬性要求：
1. 只能依据输入的论文卡片信息生成对比数据，不要使用外部知识补全。
2. 如果复杂度、场景或数据驱动属性无法从卡片中明确推断，必须写“未明确说明”或“无法确定”，不得编造。
3. 优先使用简洁、可比较、适合表格展示的短语。
4. 你必须为每篇论文输出一行结构化数据。
5. 输出不得包含解释性文本或额外字段。
You must respond with a valid JSON array of objects. Do not include any introductory or concluding text. Markdown formatting codeblocks like ```json ... ``` are strictly forbidden. Output ONLY the raw JSON string.
"""


@dataclass(slots=True)
class CardRecord:
    """Normalized paper card loaded from the JSONL file."""

    title: str
    problem: str
    key_idea: str
    method: str
    dataset_or_scenario: str
    metrics: str
    results_summary: str
    innovation_type: str
    limitations: str
    best_fit_category: str
    confidence_level: int | str


class TaxonomyResponse(BaseModel):
    """Structured markdown payload returned by the taxonomy step."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    taxonomy_markdown: str


class ComparisonRow(BaseModel):
    """One comparison row with an explicit title identifier."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    paper_title: str
    method_name: str
    time_space_complexity: str
    application_scenario: str
    pros_cons: str
    data_driven: str


class ComparisonBatchResponse(BaseModel):
    """Structured rows for one batch of papers."""

    model_config = ConfigDict(extra="forbid", str_strip_whitespace=True)

    rows: list[ComparisonRow]


def call_with_retry(func, *args, **kwargs):
    """Run external API call with bounded retry/backoff."""

    for attempt in Retrying(
        stop=stop_after_attempt(3),
        wait=wait_exponential(multiplier=1, min=1, max=8),
        retry=retry_if_exception_type(Exception),
        reraise=True,
    ):
        with attempt:
            return func(*args, **kwargs)


def dump_failure_payload(stage: str, content_text: str, extra: dict[str, object] | None = None) -> Path:
    """Persist failing model payload for parser debugging."""

    DEFAULT_DEBUG_DIR.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.utcnow().strftime("%Y%m%dT%H%M%S%fZ")
    output_path = DEFAULT_DEBUG_DIR / f"{stage}_{timestamp}.json"
    payload = {"stage": stage, "response_text": content_text}
    if extra:
        payload["meta"] = extra
    output_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    return output_path


def build_parser() -> argparse.ArgumentParser:
    """Build the command-line interface for the cluster analysis stage."""
    parser = argparse.ArgumentParser(
        description="Generate taxonomy and comparison artifacts from paper cards."
    )
    parser.add_argument(
        "--cards-path",
        type=Path,
        default=DEFAULT_CARDS_PATH,
        help="Input JSONL file generated by generate_cards.py.",
    )
    parser.add_argument(
        "--taxonomy-output",
        type=Path,
        default=DEFAULT_TAXONOMY_PATH,
        help="Output Markdown file for the taxonomy.",
    )
    parser.add_argument(
        "--comparison-output",
        type=Path,
        default=DEFAULT_COMPARISON_PATH,
        help="Output CSV file for the comparison table.",
    )
    parser.add_argument(
        "--model",
        type=str,
        default=DEFAULT_MODEL,
        help="OpenAI-compatible model name.",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=DEFAULT_BATCH_SIZE,
        help="How many paper cards to include in each comparison batch.",
    )
    parser.add_argument(
        "--sleep-seconds",
        type=float,
        default=DEFAULT_SLEEP_SECONDS,
        help="Pause between LLM calls to reduce rate-limit pressure.",
    )
    parser.add_argument(
        "--temperature",
        type=float,
        default=0.2,
        help="LLM temperature used for taxonomy and comparison generation.",
    )
    return parser


def load_cards(cards_path: Path) -> list[CardRecord]:
    """Load paper cards from JSONL and normalize them into dataclass records."""

    if not cards_path.exists():
        raise FileNotFoundError(f"Card file not found: {cards_path}")

    cards: list[CardRecord] = []
    with cards_path.open("r", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            line = line.strip()
            if not line:
                continue

            try:
                payload = json.loads(line)
            except json.JSONDecodeError:
                LOGGER.warning("Skipping invalid JSONL line %d in %s", line_number, cards_path)
                continue

            if not isinstance(payload, dict):
                continue

            try:
                card = CardRecord(
                    title=str(payload["title"]).strip(),
                    problem=str(payload["problem"]).strip(),
                    key_idea=str(payload["key_idea"]).strip(),
                    method=str(payload["method"]).strip(),
                    dataset_or_scenario=str(payload["dataset_or_scenario"]).strip(),
                    metrics=str(payload["metrics"]).strip(),
                    results_summary=str(payload["results_summary"]).strip(),
                    innovation_type=str(payload["innovation_type"]).strip(),
                    limitations=str(payload["limitations"]).strip(),
                    best_fit_category=str(payload["best_fit_category"]).strip(),
                    confidence_level=payload["confidence_level"],
                )
            except KeyError as exc:
                LOGGER.warning("Skipping incomplete card on line %d: missing %s", line_number, exc)
                continue

            if not card.title or not card.key_idea or not card.best_fit_category:
                LOGGER.warning("Skipping card with empty required fields on line %d", line_number)
                continue

            cards.append(card)

    return cards


def build_taxonomy_input(cards: list[CardRecord]) -> str:
    """Summarize all cards into a compact prompt payload for taxonomy design."""

    category_counter = Counter(card.best_fit_category for card in cards)
    category_examples: dict[str, list[str]] = defaultdict(list)
    for card in cards:
        if len(category_examples[card.best_fit_category]) < 3:
            category_examples[card.best_fit_category].append(card.key_idea)

    lines: list[str] = []
    lines.append("论文技术标签统计：")
    for category, count in category_counter.most_common():
        examples = "；".join(category_examples[category])
        lines.append(f"- {category}（{count}篇）：{examples}")

    lines.append("\n全部论文清单：")
    for index, card in enumerate(cards, start=1):
        lines.append(
            f"{index}. title={card.title} | category={card.best_fit_category} | key_idea={card.key_idea}"
        )

    return "\n".join(lines)


def create_client() -> OpenAI:
    """Create an OpenAI-compatible client from environment variables."""

    load_dotenv()
    base_url = os.getenv("OPENAI_BASE_URL") or os.getenv("OPENAI_API_BASE")
    api_key = os.getenv("OPENAI_API_KEY")

    if base_url:
        os.environ.setdefault("OPENAI_API_BASE", base_url)
    if api_key:
        os.environ.setdefault("OPENAI_API_KEY", api_key)

    try:
        return OpenAI(api_key=api_key, base_url=base_url) if (api_key or base_url) else OpenAI()
    except TypeError:
        return OpenAI()


def generate_taxonomy(client: OpenAI, model: str, temperature: float, cards: list[CardRecord]) -> str:
    """Ask the LLM to synthesize a markdown taxonomy from all card categories."""
    messages = [
        {"role": "system", "content": TAXONOMY_SYSTEM_PROMPT},
        {
            "role": "user",
            "content": (
                "请基于以下论文卡片统计，输出一份可直接保存为 Markdown 文件的分类树体系。\n\n"
                + build_taxonomy_input(cards)
            ),
        },
    ]

    try:
        response = call_with_retry(
            client.beta.chat.completions.parse,
            model=model,
            temperature=temperature,
            messages=messages,
            response_format=TaxonomyResponse,
        )
        message = response.choices[0].message
        parsed = getattr(message, "parsed", None)
        if parsed is None:
            raise ValueError("The model response did not contain parsed taxonomy output.")
        if isinstance(parsed, TaxonomyResponse):
            return parsed.taxonomy_markdown.strip()
        return TaxonomyResponse.model_validate(parsed).taxonomy_markdown.strip()
    except Exception as exc:
        LOGGER.debug("Structured parse unavailable for taxonomy; falling back to text parse: %s", exc)

    # Fallback: normal chat completion then extract taxonomy markdown from text
    completion = call_with_retry(
        client.chat.completions.create,
        model=model,
        temperature=temperature,
        messages=messages,
    )
    message = completion.choices[0].message
    content_text = None
    if hasattr(message, "content"):
        content_text = getattr(message, "content")
    elif hasattr(message, "text"):
        content_text = getattr(message, "text")
    elif isinstance(message, dict):
        content_text = message.get("content") or message.get("text")

    if isinstance(content_text, list):
        content_text = "".join(str(p) for p in content_text)

    if not isinstance(content_text, str):
        raise ValueError("Unable to extract taxonomy markdown from model response.")

    return content_text.strip()


def build_comparison_input(batch: list[CardRecord]) -> str:
    """Format a comparison batch for the LLM."""

    lines: list[str] = []
    for index, card in enumerate(batch, start=1):
        lines.append(
            "\n".join(
                [
                    f"[{index}] title: {card.title}",
                    f"problem: {card.problem}",
                    f"key_idea: {card.key_idea}",
                    f"method: {card.method}",
                    f"dataset_or_scenario: {card.dataset_or_scenario}",
                    f"metrics: {card.metrics}",
                    f"results_summary: {card.results_summary}",
                    f"innovation_type: {card.innovation_type}",
                    f"limitations: {card.limitations}",
                    f"best_fit_category: {card.best_fit_category}",
                ]
            )
        )
    return "\n\n".join(lines)


def generate_comparison_batch(
    client: OpenAI,
    model: str,
    temperature: float,
    batch: list[CardRecord],
) -> list[dict[str, object]]:
    """Ask the LLM to produce structured comparison rows for one batch."""
    messages = [
        {"role": "system", "content": COMPARISON_SYSTEM_PROMPT},
        {
            "role": "user",
            "content": (
                "请把以下论文整理成方法对比表。每篇论文必须输出一行，且字段仅限：\n"
                "paper_title, method_name, time_space_complexity, application_scenario, pros_cons, data_driven。\n\n"
                + build_comparison_input(batch)
            ),
        },
    ]

    try:
        response = call_with_retry(
            client.beta.chat.completions.parse,
            model=model,
            temperature=temperature,
            messages=messages,
            response_format=ComparisonBatchResponse,
        )
        message = response.choices[0].message
        parsed = getattr(message, "parsed", None)
        if parsed is None:
            raise ValueError("The model response did not contain parsed comparison output.")
        batch_response = parsed if isinstance(parsed, ComparisonBatchResponse) else ComparisonBatchResponse.model_validate(parsed)
        return [row.model_dump() for row in batch_response.rows]
    except Exception as exc:
        LOGGER.debug("Structured parse unavailable for comparison batch; falling back to text parse: %s", exc)

    completion = call_with_retry(
        client.chat.completions.create,
        model=model,
        temperature=temperature,
        messages=messages,
    )
    message = completion.choices[0].message
    content_text = None
    if hasattr(message, "content"):
        content_text = getattr(message, "content")
    elif hasattr(message, "text"):
        content_text = getattr(message, "text")
    elif isinstance(message, dict):
        content_text = message.get("content") or message.get("text")

    if isinstance(content_text, list):
        content_text = "".join(str(p) for p in content_text)

    if not isinstance(content_text, str) or not content_text.strip():
        raise ValueError("The model response did not contain a parsable comparison payload.")

    # Clean Markdown code fences like ```json ... ```
    m_block = re.search(r"```\s*json\s*([\s\S]*?)```", content_text, flags=re.IGNORECASE)
    if m_block:
        content_text = m_block.group(1).strip()

    # Try to extract JSON array or object with 'rows' key
    try:
        payload = json.loads(content_text)
    except Exception:
        # Fallback 1: try to extract first [...] block (common for arrays)
        start_idx = content_text.find('[')
        end_idx = content_text.rfind(']')
        if start_idx != -1 and end_idx != -1 and end_idx > start_idx:
            try:
                payload = json.loads(content_text[start_idx : end_idx + 1])
            except Exception:
                payload = None
        else:
            payload = None

        # Fallback 2: try to extract first {...} block
        if payload is None:
            start_idx = content_text.find('{')
            end_idx = content_text.rfind('}')
            if start_idx != -1 and end_idx != -1 and end_idx > start_idx:
                try:
                    payload = json.loads(content_text[start_idx : end_idx + 1])
                except Exception as exc:
                    raise ValueError(f"Failed to parse JSON from model text for comparison batch: {exc}")

        if payload is None:
            debug_path = dump_failure_payload(
                "cluster_comparison_parse",
                content_text,
                {"batch_size": len(batch), "titles": [card.title for card in batch]},
            )
            LOGGER.error("Saved failing comparison payload to %s", debug_path)
            raise ValueError("Failed to locate JSON array/object in model text response for comparison batch.")

    if isinstance(payload, dict) and "rows" in payload:
        rows = payload["rows"]
    elif isinstance(payload, list):
        rows = payload
    else:
        raise ValueError("Parsed comparison payload is not in expected format (rows list or object with 'rows').")

    validated: list[dict[str, object]] = []
    for row in rows:
        validated.append(ComparisonRow.model_validate(row).model_dump())
    return validated


def save_taxonomy(taxonomy_md: str, taxonomy_output: Path) -> None:
    """Save the taxonomy markdown file."""

    taxonomy_output.parent.mkdir(parents=True, exist_ok=True)
    taxonomy_output.write_text(taxonomy_md.strip() + "\n", encoding="utf-8")


def save_comparison_table(rows: list[dict[str, object]], comparison_output: Path) -> None:
    """Clean the comparison rows and save them as CSV with pandas."""

    comparison_output.parent.mkdir(parents=True, exist_ok=True)
    dataframe = pd.DataFrame(rows)

    preferred_columns = [
        "paper_title",
        "method_name",
        "time_space_complexity",
        "application_scenario",
        "pros_cons",
        "data_driven",
    ]
    available_columns = [column for column in preferred_columns if column in dataframe.columns]
    dataframe = dataframe.loc[:, available_columns].copy()

    for column in dataframe.columns:
        dataframe[column] = dataframe[column].fillna("").astype(str).str.strip()

    dataframe.drop_duplicates(subset=["paper_title"], keep="first", inplace=True)
    dataframe.to_csv(comparison_output, index=False, encoding="utf-8-sig")


def chunk_cards(cards: list[CardRecord], batch_size: int) -> list[list[CardRecord]]:
    """Split cards into fixed-size batches."""

    if batch_size <= 0:
        return [cards]
    return [cards[index : index + batch_size] for index in range(0, len(cards), batch_size)]


def main() -> int:
    """Run the cluster analysis stage from the command line."""

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    parser = build_parser()
    args = parser.parse_args()
    # Strictly prefer OPENAI_MODEL env var; fallback to deepseek-v4-pro
    args.model = os.getenv("OPENAI_MODEL", "deepseek-v4-pro")

    try:
        cards = load_cards(args.cards_path)
    except Exception as exc:  # noqa: BLE001 - CLI failure should be explicit.
        LOGGER.exception("Failed to load paper cards: %s", exc)
        return 1

    if not cards:
        LOGGER.error("No valid paper cards were found in %s", args.cards_path)
        return 1

    client = create_client()
    started_at = perf_counter()

    try:
        LOGGER.info("Loaded %d paper cards from %s", len(cards), args.cards_path)

        taxonomy_md = generate_taxonomy(
            client=client,
            model=args.model,
            temperature=args.temperature,
            cards=cards,
        )
        save_taxonomy(taxonomy_md, args.taxonomy_output)
        LOGGER.info("Saved taxonomy markdown to %s", args.taxonomy_output)

        comparison_rows: list[dict[str, object]] = []
        batches = chunk_cards(cards, args.batch_size)
        for batch_index, batch in enumerate(batches, start=1):
            try:
                batch_rows = generate_comparison_batch(
                    client=client,
                    model=args.model,
                    temperature=args.temperature,
                    batch=batch,
                )
                comparison_rows.extend(batch_rows)
                LOGGER.info(
                    "Generated comparison batch %d/%d with %d papers",
                    batch_index,
                    len(batches),
                    len(batch),
                )
            except Exception as exc:  # noqa: BLE001 - keep the failed batch visible.
                LOGGER.exception("Comparison batch %d failed: %s", batch_index, exc)
            sleep(max(0.0, args.sleep_seconds))

        save_comparison_table(comparison_rows, args.comparison_output)
        LOGGER.info("Saved comparison table to %s", args.comparison_output)

    except Exception as exc:  # noqa: BLE001 - keep top-level errors explicit.
        LOGGER.exception("cluster analysis failed: %s", exc)
        return 1

    elapsed_seconds = perf_counter() - started_at
    LOGGER.info(
        "Finished cluster analysis: cards=%d comparison_rows=%d elapsed=%.2fs",
        len(cards),
        len(comparison_rows),
        elapsed_seconds,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
